"""empty message

Revision ID: 02e77e67bfab
Revises: 
Create Date: 2018-11-22 22:03:51.800680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e77e67bfab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postid', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('wx_small_app_title', sa.String(length=256), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('app_fu_title', sa.String(length=56), nullable=True),
    sa.Column('is_xpc', sa.Integer(), nullable=True),
    sa.Column('is_promote', sa.Integer(), nullable=True),
    sa.Column('is_xpc_zp', sa.Integer(), nullable=True),
    sa.Column('is_xpc_cp', sa.Integer(), nullable=True),
    sa.Column('is_xpc_fx', sa.Integer(), nullable=True),
    sa.Column('is_album', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=56), nullable=True),
    sa.Column('recent_hot', sa.Integer(), nullable=True),
    sa.Column('discussion', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('rating', sa.String(length=16), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.String(length=56), nullable=True),
    sa.Column('like_num', sa.Integer(), nullable=True),
    sa.Column('share_num', sa.Integer(), nullable=True),
    sa.Column('post_type', sa.Integer(), nullable=True),
    sa.Column('cates', sa.String(length=556), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lunbo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bannerid', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=55), nullable=True),
    sa.Column('url', sa.String(length=155), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('userid', sa.String(length=55), nullable=True),
    sa.Column('addtime', sa.String(length=55), nullable=True),
    sa.Column('uptime', sa.String(length=55), nullable=True),
    sa.Column('orderid', sa.Integer(), nullable=True),
    sa.Column('cateid', sa.Integer(), nullable=True),
    sa.Column('count_click', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=55), nullable=True),
    sa.Column('end_time', sa.String(length=55), nullable=True),
    sa.Column('extra', sa.String(length=256), nullable=True),
    sa.Column('extra_data', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bannerid')
    )
    op.create_table('savegood',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('postid', sa.String(length=50), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('savegood')
    op.drop_table('lunbo')
    op.drop_table('goods')
    # ### end Alembic commands ###
